Shape of Array

In [2]:
import numpy as np
a=np.array([1,2,3,4,5])

In [3]:
a.shape

(5,)

In [6]:
b=np.array([[1,2,3],[3,4,5]])

In [8]:
b.shape

(2, 3)

In [12]:
c=np.array([1,2,3,4,5,6,7,8,9,10,11,12])

In [15]:
new_arr=c.reshape(4,3)

In [16]:
new_arr

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [18]:
new_arr = c.reshape(2,3,2)

In [19]:
new_arr

array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6]],

       [[ 7,  8],
        [ 9, 10],
        [11, 12]]])

In [21]:
new_arr

array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6]],

       [[ 7,  8],
        [ 9, 10],
        [11, 12]]])

Flattening of array

In [34]:
import numpy as np
twoD_array=np.array([[1,2,3],[4,5,6]])
flatten_arr=twoD_array.reshape(-1)

In [35]:
flatten_arr

array([1, 2, 3, 4, 5, 6])

In [36]:
flatten_arr.shape

(6,)

Indexing the Array Like normal Python indexing

In [37]:
c

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [39]:
c[0]

1

In [40]:
c[10]

11

In [41]:
c[1]+c[2]

5

In [46]:
print(b)

[[1 2 3]
 [3 4 5]]


In [45]:
print("2nd element on 1st row : " ,b[0,1])

2nd element on 1st row :  2


Array Iteration

In [3]:
import numpy as np
arr1 = np.array([1,2,3,4,5])
for x in arr1:
    print(x)

1
2
3
4
5


In [10]:
import numpy as np
arr2 = np.array([[1, 2, 3], [3, 4, 5]])
for x in arr2:
    for y in x:
        print(y)

1
2
3
3
4
5


Slicing of Array same ad python

In [14]:
import numpy as np
a1 = np.array([1,2,3,4,5,6,7])
a1[1:5]

array([2, 3, 4, 5])

In [15]:
a2 = np.array([[1, 2, 3], [3, 4, 5]])
a2[1,[1,2]]

array([4, 5])

Searching and Sorting

In [17]:
import numpy as np
arr = np.array([1,2,3,4,5,6,7,8,9,10])
x = np.where(arr==4)

In [19]:
print(x) # Returns the index of the element

(array([3], dtype=int64),)


In [20]:
y= np.where(arr%2 == 0)
print(y)

(array([1, 3, 5, 7, 9], dtype=int64),)


In [21]:
arr1=[4,5,7,2,6,2,8,2,9,10]
print(np.sort(arr1))

[ 2  2  2  4  5  6  7  8  9 10]


In [22]:
arr2=['banana','joyboy','jackfruit']
print(np.sort(arr2))

['banana' 'jackfruit' 'joyboy']
